<?php
declare(strict_types=1);
namespace MyPlot\task;

use MyPlot\MyPlot;
use MyPlot\Plot;
use pocketmine\block\Block;
use pocketmine\math\Vector3;
use pocketmine\Player;
use pocketmine\scheduler\Task;

class WandTask extends Task {
	/** @var MyPlot $plugin */
	private $plugin;
	private $plot, $level, $height, $plotWallBlock, $plotBeginPos, $xMax, $zMax;

	/**
	 * WandPlotTask constructor.
	 *
	 * @param MyPlot $plugin
	 * @param Plot $plot
	 */
	public function __construct(MyPlot $plugin, Plot $plot, $id, $d) {
        $this->id = $id;
		$this->d = $d;
		$this->plugin = $plugin;
		$this->plot = $plot;
		$this->plotBeginPos = $plugin->getPlotPosition($plot);
		$this->level = $this->plotBeginPos->getLevel();
		$this->plotBeginPos = $this->plotBeginPos->subtract(1,0,1);
		$plotLevel = $plugin->getLevelSettings($plot->levelName);
		$plotSize = $plotLevel->plotSize;
		$this->xMax = $this->plotBeginPos->x + $plotSize + 1;
		$this->zMax = $this->plotBeginPos->z + $plotSize + 1;
		$this->height = $plotLevel->groundHeight;
		$this->plotWallBlock = Block::get($this->id,$this->d);
		$this->y = 1;
	}

	/**
	 * @param int $currentTicks
	 */
	public function onRun(int $currentTick) : void {
		for($x = $this->plotBeginPos->x; $x <= $this->xMax; $x++) {
			$this->level->setBlock(new Vector3($x, 1, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 1, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 2, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 2, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 3, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 3, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 4, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 4, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 5, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 5, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 6, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 6, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 7, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 7, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 8, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 8, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 9, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 9, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 10, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 10, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 11, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 11, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 12, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 12, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 13, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 13, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 14, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 14, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 15, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 15, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 16, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 16, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 17, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 17, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 18, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 18, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 19, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 19, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 20, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 20, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 21, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 21, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 22, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 22, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 23, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 23, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 24, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 24, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 25, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 25, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 26, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 26, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 27, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 27, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 28, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 28, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 29, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 29, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 30, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 30, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 31, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 31, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 32, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 32, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 33, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 33, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 34, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 34, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 35, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 35, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 36, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 36, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 37, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 37, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 38, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 38, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 39, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 39, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 40, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 40, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 41, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 41, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 42, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 42, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 43, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 43, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 44, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 44, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 45, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 45, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 46, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 46, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 47, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 47, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 48, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 48, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 49, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 49, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 50, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 50, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 51, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 51, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 52, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 52, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 53, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 53, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 54, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 54, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 55, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 55, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 56, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 56, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 57, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 57, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 58, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 58, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 59, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 59, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 60, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 60, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 61, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 61, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 62, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 62, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 63, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 63, $this->zMax), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 64, $this->plotBeginPos->z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($x, 64, $this->zMax), $this->plotWallBlock, false, false);
		}
		for($z = $this->plotBeginPos->z; $z <= $this->zMax; $z++) {
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 1, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 1, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 2, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 2, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 3, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 3, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 4, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 4, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 5, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 5, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 6, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 6, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 7, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 7, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 8, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 8, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 9, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 9, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 10, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 10, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 11, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 11, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 12, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 12, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 13, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 13, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 14, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 14, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 15, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 15, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 16, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 16, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 17, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 17, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 18, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 18, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 19, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 19, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 20, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 20, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 21, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 21, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 22, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 22, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 23, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 23, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 24, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 24, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 25, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 25, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 26, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 26, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 27, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 27, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 28, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 28, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 29, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 29, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 30, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 30, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 31, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 31, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 32, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 32, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 33, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 33, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 34, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 34, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 35, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 35, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 36, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 36, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 37, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 37, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 38, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 38, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 39, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 39, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 40, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 40, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 41, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 41, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 42, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 42, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 43, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 43, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 44, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 44, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 45, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 45, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 46, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 46, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 47, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 47, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 48, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 48, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 49, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 49, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 50, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 50, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 51, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 51, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 52, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 52, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 53, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 53, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 54, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 54, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 55, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 55, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 56, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 56, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 57, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 57, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 58, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 58, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 59, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 59, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 60, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 60, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 61, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 61, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 62, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 62, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 63, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 63, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->plotBeginPos->x, 64, $z), $this->plotWallBlock, false, false);
			$this->level->setBlock(new Vector3($this->xMax, 64, $z), $this->plotWallBlock, false, false);
		}
	}
}
